export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_PHOTO = 'ADD_PHOTO';
export const SET_CURRENTUSER = 'SET_CURRENTUSER';
export const WRITE_TEXTAREA_VALUE = 'WRITE_TEXTAREA_VALUE';
export const LIKES_COUNT = 'LIKES_COUNT';
export const DISLIKES_COUNT = 'DISLIKES_COUNT';
