export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_PHOTO = 'ADD_PHOTO';
export const SET_CURRENTUSER = 'SET_CURRENTUSER';
export const WRITE_TEXTAREA_VALUE = 'WRITE_TEXTAREA_VALUE';
export const LIKES_COUNT_PLUS = 'LIKES_COUNT_PLUS';
export const LIKES_COUNT_MINUS = 'LIKES_COUNT_MINUS';
